// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IconsTestCom: typeof import('./components/icons/TestCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}

export {}
